name: Workflow C calls Workflow B from reusable-workflow-test2.

on:
  workflow_dispatch:
    inputs:
      input_message:
        description: 'Message to pass to Workflow B'
        required: true

jobs:
  call-workflow-b:
    uses: popup-mainframe/Dshirisha17/reusable-workflow-test2/.github/workflows/workflow-b.yml@main
    with:
      input_message: ${{ github.event.inputs.input_message }}  # Pass input from Workflow C to Workflow B
